
name: Actualizad Pi y Arduino

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
      - name: Salvando el Pollo
        env:
          POLLO_SECRETO: ${{ secrets.POLLO_SECRETO }}
        run: |
          echo $POLLO_SECRETO >> Token.js
      - name: Parar NodeJs
        run: pm2 stop ambiente
      - name: Compilar codigo Arduino
        run: arduino-cli compile -b arduino:avr:uno Arduino_Temperatura/
      - name: Subir codigo Arduino
        run: arduino-cli upload -p /dev/ttyACM0 -b arduino:avr:uno Arduino_Temperatura/
      - name: instalando paquetes nodejs
        run: npm install -s
      - name: Reiniciando NodeJs
        run: pm2 start ambiente
