
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        arduino-platform: ["arduino:avr"]
        include:
          - arduino-platform: "arduino:avr"
            fqbn: "arduino:avr:unowifi"

    steps:
      - uses: actions/checkout@master
      - name: Configurando Arduino CLI
        uses: arduino/setup-arduino-cli@v1.0.0
      - name: Install platform Arduino CLI
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.arduino-platform }}
      - name: Salvando el Pollo
        env:
          POLLO_SECRETO: ${{ secrets.POLLO_SECRETO }}
        run: |
          echo $POLLO_SECRETO >> Pollo.txt
      - name: Run a one-line script
        run: pm2 stop 1
      # - name: instalando paquetes nodejs
        # run: npm install
      - name: Run a multi-line script
        run: |
          echo "hola mundo extra" >> hola.txt
          pm2 start 1
