
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
      - name: Salvando el Pollo
        env:
          POLLO_SECRETO: ${{ secrets.POLLO_SECRETO }}
        run: |
          echo $POLLO_SECRETO >> Pollo.txt
      - name: Parar NodeJs
        run: pm2 stop 1
      # - name: instalando paquetes nodejs
        # run: npm install
      - name: Compilar codigo Arduino
        run: arduino-cli compile -b arduino:avr:uno Arduino_Temperatura/
        shell: bash
      - name: Reiniciando NodeJs
        run: |
          echo "hola mundo extra" >> hola.txt
          pm2 start 1
